version: 2 

sources: 
  - name: 'src_seed'
    database: portable
    schema: prt_src 
    tables:
    - name: a_advisor 
    - name: b_contract 
    - name: c_client 
    - name: d_date 
    - name: e_product 
    - name: f_combined 
