
broker: 'pyamqp://guest:guest@localhost//'  # Optional[str]: The URL of the Celery broker
backend: 'rpc://' # Optional[str]: The URL of the Celery results backend
include: ['execution_patterns.ELT-graph'] # Optional[List[str]]: Modules every worker should import
config_source: # Dict[str, Any]: Any additional parameters to pass to the workers
  broker_pool_limit: 10 
  broker_connection_timeout: 10
  broker_transport_options: 
    max_retries: 2, 
    interval_start: 0, 
    interval_step: 0.5, 
    interval_max: 1, 

  worker_send_task_events: False 
  worker_concurrency: 4 
  worker_prefetch_multiplier: 2 

  task_create_missing_queues: True 
  task_default_queue: dagster 
  task_default_exchange: default 
  task_default_routing_key: default_route 
  task_default_priority: 5 
  task_queue_max_priority: 10 
  task_always_eager: False 
  task_queues: 
    - name: dagster 
      exchange: default 
      routing_key: default_route 
    - name: extract_queue 
      exchange: extract 
      routing_key: extract_pipeline 
    - name: loading_queue 
      exchange: loading 
      routing_key: loading_pipeline 
    - name: compute_queue 
      exchange: compute 
      routing_key: compute_pipeline 

