
broker: 'pyamqp://rabbit@localhost//'  # Optional[str]: The URL of the Celery broker
backend: 'rpc://' # Optional[str]: The URL of the Celery results backend
include: ['execution_patterns/ELT-graph.py'] # Optional[List[str]]: Modules every worker should import
config_source: # Dict[str, Any]: Any additional parameters to pass to the workers
  worker_concurrency: 4 
  worker_prefetch_multiplier: 2 
  worker_send_task_events: enable
  broker_pool_limit: 10 
  task_annotations: 
    tasks.add: 
      rate_limit: '1/s'
  task_queues: 
    - name: celery 
      exchange: default 
      routing_key: default 
    - name: extract_queue 
      exchange: extract 
      routing_key: extract_pipe 
    - name: loading_queue 
      exchange: loading 
      routing_key: loading_pipe 
    - name: compute_queue 
      exchange: compute 
      routing_key: compute_pipe 
  task_default_queue: 'celery' 
  task_default_exchange: 'default' 
  task_default_routing_key: 'default_route' 
      





